loadding data
reading category information





100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 136710/136710 [00:13<00:00, 9905.12it/s]
reading train data



100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2571752/2571752 [00:05<00:00, 455864.33it/s]
reading valid data
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 845781/845781 [00:01<00:00, 427948.99it/s]
reading test data
get weight for each sample
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 136710/136710 [00:00<00:00, 2040566.61it/s]
Traceback (most recent call last):
  File "main.py", line 54, in <module>
    score_pos, score_neg,loss_moe = model(graph_pos, graph_neg)
  File "/home/gwy/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gwy/BaseSAT/BaseGAT/models/models.py", line 69, in forward
    h,loss = self.get_embedding()
  File "/home/gwy/BaseSAT/BaseGAT/models/models.py", line 208, in get_embedding
    muti_int,h_user = layer(self.graph, h, ('item', 'rated by', 'user'))
  File "/home/gwy/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gwy/BaseSAT/BaseGAT/models/layers.py", line 232, in forward
    graph.update_all(self.category_aggregation, self.sub_reduction_item_user, etype = etype)
  File "/home/gwy/anaconda3/envs/PyTorch/lib/python3.8/site-packages/dgl/heterograph.py", line 4781, in update_all
    ndata = core.message_passing(g, message_func, reduce_func, apply_node_func)
  File "/home/gwy/anaconda3/envs/PyTorch/lib/python3.8/site-packages/dgl/core.py", line 407, in message_passing
    ndata = invoke_udf_reduce(g, rfunc, msgdata, orig_nid=orig_nid)
  File "/home/gwy/anaconda3/envs/PyTorch/lib/python3.8/site-packages/dgl/core.py", line 159, in invoke_udf_reduce
    bkt_rsts.append(func(nbatch))
  File "/home/gwy/BaseSAT/BaseGAT/models/layers.py", line 192, in sub_reduction_item_user
    muti_int=self.poly_attn(embeddings=mail, attn_mask=0, bias=None)
  File "/home/gwy/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gwy/BaseSAT/BaseGAT/models/layers.py", line 278, in forward
    proj = th.tanh(self.linear(embeddings))
  File "/home/gwy/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gwy/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
model already setting